[package]
name = "oasis-core-runtime"
version = "0.3.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[dependencies]
log = "0.4"
slog = "2.7.0"
slog-json = "2.3.0"
slog-scope = "4.4.0"
slog-stdlog = "4.1.0"
serde = { version = "1.0.123", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = "1.0.62"
serde_bytes = "0.11.5"
serde_repr = "0.1.5"
lazy_static = "1.3.0"
crossbeam = "0.8.0"
byteorder = "1.4.2"
anyhow = "1.0"
thiserror = "1.0"
sgx-isa = { version = "0.3.3", features = ["sgxstd"] }
webpki = "0.21.2"
untrusted = "0.7.0"
bincode = "1.0.0"
snow = { version = "0.7.2", default-features = false, features = ["ring-accelerated"] }
percent-encoding = "2.1.0"
pem = "0.8.2"
chrono = "0.4.19"
base64 = "0.13.0"
rustc-hex = "2.0.1"
rand = "0.8.3"
futures = "0.1.25"
tokio-current-thread = "0.1.5"
tokio-executor = "0.1.6"
io-context = "0.2.0"
x25519-dalek = "1.1.0"
ed25519-dalek = "1.0.1"
deoxysii = { git = "https://github.com/oasisprotocol/deoxysii-rust" }
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
sp800-185 = "0.2.0"
zeroize = "1.2"
intrusive-collections = "0.8"
sha2 = "0.9.3"
hmac = "0.10.1"
honggfuzz = "0.5.52"
arbitrary = { version = "0.4.7", features = ["derive"] }
num-bigint = { version = "0.3", features = ["serde"] }
num-traits = "0.2.14"
bech32 = "0.7.2"

[dev-dependencies]
# For storage interoperability tests only.
grpcio = "0.4.6"
tempfile = "3.2.0"

[[bin]]
name = "fuzz-mkvs-proof"
path = "fuzz/mkvs_proof.rs"

[[bin]]
name = "fuzz-mkvs-node"
path = "fuzz/mkvs_node.rs"
